/**
 * Automatically generated by @grafana/openapi-to-k6: 0.4.1
 * Do not edit manually.
 * VC_SL
 * Service version: 1.0
 */
import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js";

import http from "k6/http";
import type { Params, Response } from "k6/http";

export interface CreateUserDto {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  id: number;
  /** @nullable */
  usernameHistory?: string | null;
}

export type LeaderboardCategory =
  (typeof LeaderboardCategory)[keyof typeof LeaderboardCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeaderboardCategory = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;

export interface LeaderboardDto {
  rank?: number;
  userId?: number;
  /** @nullable */
  username?: string | null;
  winrate?: number;
  monthsPlayed?: number;
}

export type LeaderboardPeriod =
  (typeof LeaderboardPeriod)[keyof typeof LeaderboardPeriod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeaderboardPeriod = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}

export interface UpdateUserDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  usernameHistory: string;
}

export interface UpdateWinrateDto {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  userId: number;
  /**
   * @minimum 1
   * @maximum 12
   */
  month: number;
  /**
   * @minimum 2000
   * @maximum 2100
   */
  year: number;
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  baseAttackWinrate?: number | null;
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  baseDefenceWinrate?: number | null;
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  fleetWinrate?: number | null;
}

export interface UserDto {
  id?: number;
  /** @nullable */
  usernameHistory?: string[] | null;
  createdAt?: string;
  updatedAt?: string;
}

export interface WinrateDto {
  userId?: number;
  month?: number;
  year?: number;
  /** @nullable */
  baseAttackWinrate?: number | null;
  /** @nullable */
  baseDefenceWinrate?: number | null;
  /** @nullable */
  fleetWinrate?: number | null;
}

export type GetApiLeaderboardParams = {
  period?: LeaderboardPeriod;
  category?: LeaderboardCategory;
  month?: number;
  year?: number;
  limit?: number;
  minimumMonths?: number;
};

export type GetApiWinrateGetWinrateForUserParams = {
  userId?: number;
  year?: number;
};

/**
 * This is the base client to use for interacting with the API.
 */
export class VcSlClient {
  private cleanBaseUrl: string;
  private commonRequestParameters: Params;

  constructor(clientOptions: {
    baseUrl: string;
    commonRequestParameters?: Params;
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

    this.commonRequestParameters = clientOptions.commonRequestParameters || {};
  }

  getApiLeaderboard(
    params?: GetApiLeaderboardParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: LeaderboardDto[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/api/Leaderboard` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "GetApiLeaderboard",
    };
  }

  getApiUsersGetUserId(
    id: number,
    requestParameters?: Params,
  ): {
    response: Response;
    data: UserDto;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/Users/GetUser/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "GetApiUsersGetUserId",
    };
  }

  postApiUsersCreateUser(
    createUserDto: CreateUserDto,
    requestParameters?: Params,
  ): {
    response: Response;
    data: UserDto;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/Users/CreateUser`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(createUserDto),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "PostApiUsersCreateUser",
    };
  }

  putApiUsersUpdateUserId(
    id: number,
    updateUserDto: UpdateUserDto,
    requestParameters?: Params,
  ): {
    response: Response;
    data: UserDto;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/Users/UpdateUser/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      k6url.toString(),
      JSON.stringify(updateUserDto),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "PutApiUsersUpdateUserId",
    };
  }

  getApiWinrateGetWinrateForUser(
    params?: GetApiWinrateGetWinrateForUserParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: WinrateDto[];
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/api/Winrate/GetWinrateForUser` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "GetApiWinrateGetWinrateForUser",
    };
  }

  postApiWinrateUpdateWinrate(
    updateWinrateDto: UpdateWinrateDto,
    requestParameters?: Params,
  ): {
    response: Response;
    data: WinrateDto | void;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/Winrate/UpdateWinrate`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(updateWinrateDto),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "PostApiWinrateUpdateWinrate",
    };
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    };
  }
}
